services:
  web:
    build: # Dockerfileで設定する
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    depends_on:
      - php

  php:
    build: # Dockerfileで設定する
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./src:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  mysql:
    build: # Dockerfileで設定する
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=1729
      - MYSQL_DATABASE=shin
    ports:
      - 3306:3306
    volumes: # mysqlのテーブルやらなんやらを保存する
      - mysql-data:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d
volumes:
  mysql-data:
  
